stages:
  data_generation:
    cmd: python -m src.data_generation.main --users 10000 --products 1000 --interactions
      100000
    deps:
    - src/data_generation/
    - src/utils/
    - config/
    - requirements.txt
    outs:
    - data/raw/users/users.parquet:
        persist: true
    - data/raw/products/products.parquet:
        persist: true
    - data/raw/interactions/interactions.parquet:
        persist: true
    - data/raw/categories/categories.parquet:
        persist: true
    - data/raw/metadata/generation_metadata.json:
        persist: true
    meta:
      name: Generate synthetic e-commerce data
      description: Create synthetic users, products, interactions, and categories
      tags: [data, generation, synthetic]
  data_processing:
    cmd: python -m src.processing.main
    deps:
    - config
    - data/raw
    - data/validation_report.txt
    - src/processing
    - src/utils
    outs:
    - data/features
    - data/processed
  data_validation:
    cmd: python -m src.validation.main --output-report data/validation_report.txt
      --quality-threshold 0.8
    deps:
    - config
    - data/raw
    - src/utils
    - src/validation
    outs:
    - data/validation_report.txt
